runtime: python39
entrypoint: gunicorn -b :$PORT app:app

handlers:
  - url: /
    static_files: frontend/index.html
    upload: frontend/index.html

  - url: /(.*)
    static_files: frontend/\1
    upload: frontend/(.*)
