<?php
$array1=array(array(77,87),array(23,45));
$array2=array("yahoo","com");
$result=array();
for($i=0;$i<count($array1);$i++)
{
	$result[]=array_merge($array1[$i],array($array2[$i]));
}
print_r($result);
?>	